# Generated by Django 4.1.7 on 2023-03-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_image_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gc_id',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
